#!/bin/bash

action="XX"
if [ X$1 != "X" ]
then
  action=$1
fi

# this playbook sets up the VMs to be part of a cluster.
if [ ${action} == "install" ]
then
  ansible-playbook -i hosts5 hosts5play.yml
  exit 0
fi


# repairs damage from install and restarts the daemons
if [ ${action} == "post" ]
then
  ansible-playbook -i hosts5 hosts5post1.yml
  exit 0
fi

echo "hosts5run install|post"
exit 1

