#!/bin/bash

# This requires python3
ansible-playbook -i osehosts /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml -e 'ansible_python_interpreter=/usr/bin/python3'
#ansible-playbook -i osehosts /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-node/config.yml -e 'ansible_python_interpreter=/usr/bin/python3'
#ansible-playbook -i osehosts /usr/share/ansible/openshift-ansible/playbooks/adhoc/uninstall.yml -e 'ansible_python_interpreter=/usr/bin/python3'

